package com.awakenedredstone.testmod;

import io.wispforest.owo.config.annotation.Config;
import io.wispforest.owo.ui.core.Color;
import net.minecraft.util.Identifier;

import java.util.UUID;

@SuppressWarnings("unused")
@Config(name = "test", wrapperName = "TestConfig")
public class TestConfigCore {
    public int integer = 0;
    public String string = "";
    public Color color = Color.WHITE;
    public Identifier identifier = new Identifier("example:test");
    public UUID uuid = new UUID(0, 0);
    public String potion = "none";
    public boolean test1 = true;
    public boolean test2 = true;
    public boolean test3 = true;
    public boolean test4 = true;
    public boolean test5 = true;
    public boolean test6 = true;
    public boolean test7 = true;
    public boolean test8 = true;
    public boolean test9 = true;
    public boolean test10 = true;
    public boolean test11 = true;
    public boolean test12 = true;
    public boolean test13 = true;
    public boolean test14 = true;
    public boolean test15 = true;
    public boolean test16 = true;
    public boolean test17 = true;
    public boolean test18 = true;
    public boolean test19 = true;
    public boolean test20 = true;
    public boolean test21 = true;
    public boolean test22 = true;
    public boolean test23 = true;
    public boolean test24 = true;
    public boolean test25 = true;
    public boolean test26 = true;
    public boolean test27 = true;
    public boolean test28 = true;
    public boolean test29 = true;
    public boolean test30 = true;
    public boolean test31 = true;
    public boolean test32 = true;
    public boolean test33 = true;
    public boolean test34 = true;
    public boolean test35 = true;
    public boolean test36 = true;
    public boolean test37 = true;
    public boolean test38 = true;
    public boolean test39 = true;
    public boolean test40 = true;
    public boolean test41 = true;
    public boolean test42 = true;
    public boolean test43 = true;
    public boolean test44 = true;
    public boolean test45 = true;
    public boolean test46 = true;
    public boolean test47 = true;
    public boolean test48 = true;
    public boolean test49 = true;
    public boolean test50 = true;
    public boolean test51 = true;
    public boolean test52 = true;
    public boolean test53 = true;
    public boolean test54 = true;
    public boolean test55 = true;
    public boolean test56 = true;
    public boolean test57 = true;
    public boolean test58 = true;
    public boolean test59 = true;
    public boolean test60 = true;
    public boolean test61 = true;
    public boolean test62 = true;
    public boolean test63 = true;
    public boolean test64 = true;
    public boolean test65 = true;
    public boolean test66 = true;
    public boolean test67 = true;
}
